#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v24
# autospec commit: a88ffdc
#
Name     : R-gss
Version  : 2.2.9
Release  : 56
URL      : https://ftp.osuosl.org/pub/cran/src/contrib/gss_2.2-9.tar.gz
Source0  : https://ftp.osuosl.org/pub/cran/src/contrib/gss_2.2-9.tar.gz
Summary  : General Smoothing Splines
Group    : Development/Tools
License  : GPL-2.0+
Requires: R-gss-lib = %{version}-%{release}
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
function estimation using smoothing splines.

%package lib
Summary: lib components for the R-gss package.
Group: Libraries

%description lib
lib components for the R-gss package.


%prep
%setup -q -n gss
pushd ..
cp -a gss buildavx2
popd
pushd ..
cp -a gss buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1744638362

%install
export SOURCE_DATE_EPOCH=1744638362
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/gss/CITATION
/usr/lib64/R/library/gss/DESCRIPTION
/usr/lib64/R/library/gss/INDEX
/usr/lib64/R/library/gss/Meta/Rd.rds
/usr/lib64/R/library/gss/Meta/data.rds
/usr/lib64/R/library/gss/Meta/features.rds
/usr/lib64/R/library/gss/Meta/hsearch.rds
/usr/lib64/R/library/gss/Meta/links.rds
/usr/lib64/R/library/gss/Meta/nsInfo.rds
/usr/lib64/R/library/gss/Meta/package.rds
/usr/lib64/R/library/gss/NAMESPACE
/usr/lib64/R/library/gss/R/gss
/usr/lib64/R/library/gss/R/gss.rdb
/usr/lib64/R/library/gss/R/gss.rdx
/usr/lib64/R/library/gss/data/ColoCan.rda
/usr/lib64/R/library/gss/data/DiaRet.rda
/usr/lib64/R/library/gss/data/LakeAcidity.rda
/usr/lib64/R/library/gss/data/NO2.rda
/usr/lib64/R/library/gss/data/Sachs.rda
/usr/lib64/R/library/gss/data/aids.rda
/usr/lib64/R/library/gss/data/bacteriuria.rda
/usr/lib64/R/library/gss/data/buffalo.rda
/usr/lib64/R/library/gss/data/clim.rda
/usr/lib64/R/library/gss/data/datalist
/usr/lib64/R/library/gss/data/esc.rda
/usr/lib64/R/library/gss/data/eyetrack.rda
/usr/lib64/R/library/gss/data/gastric.rda
/usr/lib64/R/library/gss/data/nox.rda
/usr/lib64/R/library/gss/data/ozone.rda
/usr/lib64/R/library/gss/data/penny.rda
/usr/lib64/R/library/gss/data/stan.rda
/usr/lib64/R/library/gss/data/wesdr.rda
/usr/lib64/R/library/gss/data/wesdr1.rda
/usr/lib64/R/library/gss/help/AnIndex
/usr/lib64/R/library/gss/help/aliases.rds
/usr/lib64/R/library/gss/help/gss.rdb
/usr/lib64/R/library/gss/help/gss.rdx
/usr/lib64/R/library/gss/help/paths.rds
/usr/lib64/R/library/gss/html/00Index.html
/usr/lib64/R/library/gss/html/R.css

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/R/library/gss/libs/gss.so
/V4/usr/lib64/R/library/gss/libs/gss.so
/usr/lib64/R/library/gss/libs/gss.so
